node("$nodeLabel") {

    properties([parameters([choice(choices: ['all_test', 'all_attestation_test', 'all_non_attestation_test',
    'redis_attestation_test', 'pytorch_attestation_test', 'redis_non_attestation_test',
    'pytorch_non_attestation_test'], name: 'run'),
    string(description: 'enter the specific pytest to execute', name: 'run_specific_test'),
    string(defaultValue: 'graphene_dcap', description: '''graphene_dcap [attestation test]
    graphene_wcity_02 [non attestation test]''', name: 'nodeLabel')])])

    checkout scm
    test_executor = load 'ci/libs/utils.pipeline'

    try {
        test_executor.initialize()
        test_executor.runtest()
    } catch (Exception e){
        test_executor.storeartifacts()
        test_executor.cleanup()
    }
}